# Generated by Django 5.1.4 on 2024-12-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_tweet"),
    ]

    operations = [
        migrations.AddField(
            model_name="tweet",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="photos/"),
        ),
        migrations.AlterField(
            model_name="tweet",
            name="text",
            field=models.TextField(max_length=1000),
        ),
    ]
