# Generated by Django 5.1.4 on 2024-12-31 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_tweet_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="task",
            new_name="title",
        ),
    ]
