# Generated by Django 5.1.4 on 2024-12-31 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_rename_task_task_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="img",
            field=models.ImageField(blank=True, null=True, upload_to="photos/"),
        ),
    ]
