# Generated by Django 5.1.4 on 2024-12-31 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_task_img"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="img",
            new_name="photo",
        ),
    ]
