# Generated by Django 5.1.4 on 2024-12-31 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_rename_img_task_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="photo",
        ),
        migrations.AddField(
            model_name="task",
            name="img",
            field=models.ImageField(blank=True, null=True, upload_to="task/"),
        ),
    ]
