# Generated by Django 5.1.5 on 2025-01-15 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_comment_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='tweet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.tweet'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(default=None, max_length=1000),
        ),
    ]
