# Generated by Django 5.1.5 on 2025-01-22 10:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_comment_comment_alter_comment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='comment',
            name='tweet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='api.tweet'),
        ),
    ]
